version: "3.9"

services:
  beelzebub:
    #network_mode: host # Not work on Mac OS
    image: m4r10/beelzebub:latest
    restart: always
    ports: # Remove me, if you use configuration network_mode: host
      - "22:22"
      - "8080:8080"
      - "80:80"
    volumes:
      - "./configurations:/configurations"