version: "3.9"

services:
  beelzebub:
    container_name: beelzebub
    image: m4r10/beelzebub:v3.3.6
    restart: always
    ports:
      - "22:22"
      - "8080:8080"
      - "2222:2222"
      - "3306:3306"
      - "80:80"
      - "5432:5432"
    volumes:
      - "./configurations:/configurations"
